# Generated by Django 3.1.1 on 2020-10-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20200915_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
