# Generated by Django 3.0.6 on 2020-10-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_content_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='airtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.TextField()),
                ('img_url', models.TextField()),
            ],
        ),
    ]
