# Generated by Django 3.0.6 on 2020-10-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_airtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='airtable',
        ),
        migrations.AlterField(
            model_name='content',
            name='photo',
            field=models.TextField(),
        ),
    ]
